# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecbbd6af9bb350cc250beb161275795885c133699ae23f1679193d9ce4dc4462ee8a403c1fa4c7ee4e918b1c2ad0ef517548533b4582d502192ce94fa5dfc492

test:
  secret_key_base: 69971801330c5cabb0b1396f9f90768a2c6974076634aae20fcc399ad0de07f6798c0a4d09d9687d1b06545cbd97edc26e07f1436d5536a86895125cb32f3985

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
